POST http://localhost:8080/holder
Content-Type: application/json

{
  "holderName" : "kevin",
  "tel" : "02-1234-5678",
  "address" : "OO시 OO구"
}

###

POST http://localhost:8080/account
Content-Type: application/json

{
  "holderID" : "84363e79-4d87-4196-8789-b5b16a1a0c31"
}

###

POST http://localhost:8080/deposit
Content-Type: application/json

{
  "accountID" : "5d21a00b-0bfb-4c12-873e-108a84dab00c",
  "holderID" : "84363e79-4d87-4196-8789-b5b16a1a0c31",
  "amount" : 300
}

###

POST http://localhost:8080/withdrawal
Content-Type: application/json

{
  "accountID" : "604394b5-3fa3-49dd-a23c-605ebe448ebc",
  "holderID" : "819c571d-6899-440c-8348-57ace8aa4254",
  "amount" : 1
}

###